### ISSUE TITLE
cookie isnt ceated solution is admin rights

### ISSUE THREAD

**Issue by ecomcodeLab** [JoaoCampelo/Presearch_Bot#10]
hi i found out why sometimes the cookie isnt created in folder

i have to open cmd as admin then cd into the presearch folder and then open the presearch py if i provide the login details and press enter it creats a cookie.

**Comment by JoaoCampelo** [comment]
You can have the bot in a folder where it is only possible to create files in administrator mode, and as the bot does not open as administrator it cannot create the cookie, try to place the bot in a folder that does not need administrator permissions.

**Comment by ecomcodeLab** [comment]
on my new pc it isnt working cant create a cookie file alsow not with admin rights. i try admin rights on presearch folder i try to open py as admin i tryed to open admin with bat file from presearch not working becorse it cant find words file. then i try to let it start with task sheduler as admin not creating a cookie. i tryed other folder inside c drive not working. what can i do if the bot opens chrome and i make an new tab and login by my own it is logged in. is there a way to copy the cookie by my self ?

**Comment by JoaoCampelo** [comment]
First make sure you have all the dependencies installed, and that you have python properly configured. Then make sure you have the bot in a folder where you have write permissions, in C you don't always have write permissions and to add/delete a file you need to give administrator permissions, put the bot on the desktop for example and go back to try, if it doesn't solve I don't know what can be seen that I can't reproduce this problem.

**Comment by ecomcodeLab** [comment]
thanks for the answer but no way i tryed on 2 windows machines no way to save the cookie after captcha and enter. i try with all premissions with admin cmd and so on. alsow with a admin bat no way to do. yes it is on patition c and on desktop. i made a patition d and try there but then there is a problem with startin the bot it hangs on webdriver configure
