### ISSUE TITLE
it dosnt save cookie

### ISSUE THREAD

**Issue by ecomcodeLab** [JoaoCampelo/Presearch_Bot#7]
hi i dont know what is wrong but bot opens chrome put in my account and i provide that i not a human then i press enter inside bot but it writes "unable to login" and does not save cookie

what can  i do can i get the cookie in  other ways ??

**Comment by JoaoCampelo** [comment]
Whenever the bot logs in using the cookie, everything happens as expected, but when it is necessary to log in normally, entering the email and password, I think that in some situations an error occurs and displays the message you indicated. When this happens you have to restart the bot. in a future version I will try to understand what happens and correct it.
