### ISSUE TITLE
pip modifiy error while updating

### ISSUE THREAD

**Issue by ecomcodeLab** [JoaoCampelo/Presearch_Bot#9]
try to update but i get error

ERROR: To modify pip, please run the following command: c:\users\username\appdata\local\programs\python\python37\python.exe -m pip install -r Presearch_Bot/requirements.txt

can you help?

alsow is it modifyng pip? if yes whill this change some things inside pip so other tools want work ??

**Comment by JoaoCampelo** [comment]
Probably your version of pip is not up to date, update pip and try again.

Upgrade pip with the following command: python -m pip install --upgrade pip

Then tell me if it solved your problem.
